### ISSUE TITLE
how activate this pluggin?

### ISSUE THREAD

**Issue by igotfr** [zarathir/lapce-dart#5]
how activate this pluggin? I have already it installed on lapce

**Comment by zarathir** [comment]
Can you provide some more information?

Is there an error message? Did you set the path to the dart executable in the settings? I haven't gotten around to implement starting the LSP from `PATH`, so you have to provide this to the plugin.

**Comment by igotfr** [comment]
> Can you provide some more information?
> 
> Is there an error message? Did you set the path to the dart executable in the settings? I haven't gotten around to implement starting the LSP from `PATH`, so you have to provide this to the plugin.

`$ which dart`
`/home/notecomm/flutter/bin/dart`

@zarathir Settings > Plugin Settings > Dart > Server Path. Path to dart executable > /home/notecomm/flutter/bin/dart

it just doesn't work. No error messages

**Comment by zarathir** [comment]
Hmm, if there are no error messages the plugin should have started. Have you tried opening code completions in a dart file?
Can you check if the dart lsp process is running?

**Comment by igotfr** [comment]
@zarathir
> Hmm, if there are no error messages the plugin should have started.
> Have you tried opening code completions in a dart file?

yes

> Can you check if the dart lsp process is running?

how do i check this? I didn't see any visual indicators on the lapce

**Comment by igotfr** [comment]
@zarathir it's working on project, but in this case a message `Analyzing` flashes endlessly on lower left corner.
Too, the light bulb icon flashes when I click anywhere on text editor, but I can't click on the icon

when I open a single file, like `$ lapce file.dart`, the plugin doesn't works

**Comment by zarathir** [comment]
> how do i check this? I didn't see any visual indicators on the lapce

There's no indicator to show if the lsp is running. You can run `ps aux | grep -i dart` in a terminal to check if there is a running process.

> @zarathir it's working on project, but in this case a message `Analyzing` flashes endlessly on lower left corner. Too, the light bulb icon flashes when I click anywhere on text editor, but I can't click on the icon
> 
> when I open a single file, like `$ lapce file.dart`, the plugin doesn't works

Seems like the lsp starts, but the code actions are off. Are you able to trigger code completion with `Ctrl + Space`. 
The plugin currently only works with a dart workspace, so it won't start with single files.

**Comment by zarathir** [comment]
@cindRoberta What Lapce version are you running? I just tried the plugin on nightly and it works as usual.

**Comment by igotfr** [comment]
> @cindRoberta What Lapce version are you running? I just tried the plugin on nightly and it works as usual.

0.2.6

**Comment by igotfr** [comment]
@zarathir `Ctrl + Space` is working. `Ctrl + .` not

**Comment by zarathir** [comment]
I've got `Analyzing...` flashing up a lot aswell. This is from Lapce sending lsp requests to the plugin. There's probably not a lot you can do about this plugin wise. LSP is currently not fully implemented in Lapce, so plugin support is wonky and experimental.

**Comment by igotfr** [comment]
@zarathir the light bulb icon and the `Ctrl + .` not working, can't be fixed either?

**Comment by zarathir** [comment]
This is something that has to be fixed in Lapce. The plugin only handles starting the lsp. All the requests are coming from Lapce.
