### ISSUE TITLE
Server Args & Server Path

### ISSUE THREAD

**Issue by idnorman** [zarathir/lapce-dart#6]
Sorry, but how the path format exactly? 
and what does server args mean?
![image](https://github.com/zarathir/lapce-dart/assets/95529665/ccd32358-5392-41b6-92ac-b8bec847b5b4)

**Comment by zarathir** [comment]
Path looks fine. If there are no errors while opening a dart/flutter workspace and code completion is working the lsp is running.

Server args means you can add more command line arguments to pass to the language server. For reference which commands are supported check [here](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/api.html). Upon checking the link it seems like they removed almost all of the arguments except for the ones already passed by the plugin. So you can just leave this entry empty.
